2018-02-04 02:50:56,918 ERROR: Exception on /create [POST] [in /Users/davidliu/.virtualenvs/default3/lib/python3.5/site-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/Users/davidliu/.virtualenvs/default3/lib/python3.5/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/davidliu/.virtualenvs/default3/lib/python3.5/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/davidliu/.virtualenvs/default3/lib/python3.5/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/davidliu/.virtualenvs/default3/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/Users/davidliu/.virtualenvs/default3/lib/python3.5/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/davidliu/.virtualenvs/default3/lib/python3.5/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/davidliu/.virtualenvs/default3/lib/python3.5/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/Users/davidliu/Website/HMH-project/app/routes.py", line 226, in create
    return render_template('create.html', title = 'Create New Entry', form = form)
  File "/Users/davidliu/.virtualenvs/default3/lib/python3.5/site-packages/flask/templating.py", line 134, in render_template
    context, ctx.app)
  File "/Users/davidliu/.virtualenvs/default3/lib/python3.5/site-packages/flask/templating.py", line 116, in _render
    rv = template.render(context)
  File "/Users/davidliu/.virtualenvs/default3/lib/python3.5/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/Users/davidliu/.virtualenvs/default3/lib/python3.5/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/davidliu/.virtualenvs/default3/lib/python3.5/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/Users/davidliu/Website/HMH-project/app/templates/create.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/davidliu/Website/HMH-project/app/templates/base.html", line 2, in top-level template code
    {% import 'bootstrap/wtf.html' as wtf %}
  File "/Users/davidliu/.virtualenvs/default3/lib/python3.5/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 1, in top-level template code
    {% block doc -%}
  File "/Users/davidliu/.virtualenvs/default3/lib/python3.5/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 4, in block "doc"
    {%- block html %}
  File "/Users/davidliu/.virtualenvs/default3/lib/python3.5/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 20, in block "html"
    {% block body -%}
  File "/Users/davidliu/.virtualenvs/default3/lib/python3.5/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 23, in block "body"
    {% block content -%}
  File "/Users/davidliu/Website/HMH-project/app/templates/base.html", line 105, in block "content"
    {% block app_content %}{% endblock %}
  File "/Users/davidliu/Website/HMH-project/app/templates/create.html", line 29, in block "app_content"
    <form action="{% block form_action %}{{ url_for('entries') }}{% endblock %}" class="form-horizontal" method="post">
  File "/Users/davidliu/Website/HMH-project/app/templates/create.html", line 29, in block "form_action"
    <form action="{% block form_action %}{{ url_for('entries') }}{% endblock %}" class="form-horizontal" method="post">
  File "/Users/davidliu/.virtualenvs/default3/lib/python3.5/site-packages/flask/helpers.py", line 333, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/Users/davidliu/.virtualenvs/default3/lib/python3.5/site-packages/flask/app.py", line 1805, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/Users/davidliu/.virtualenvs/default3/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/Users/davidliu/.virtualenvs/default3/lib/python3.5/site-packages/flask/helpers.py", line 323, in url_for
    force_external=external)
  File "/Users/davidliu/.virtualenvs/default3/lib/python3.5/site-packages/werkzeug/routing.py", line 1768, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'entries'. Did you forget to specify values ['username']?
2018-02-04 02:52:13,033 ERROR: Exception on /create [GET] [in /Users/davidliu/.virtualenvs/default3/lib/python3.5/site-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/Users/davidliu/.virtualenvs/default3/lib/python3.5/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/davidliu/.virtualenvs/default3/lib/python3.5/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/davidliu/.virtualenvs/default3/lib/python3.5/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/davidliu/.virtualenvs/default3/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/Users/davidliu/.virtualenvs/default3/lib/python3.5/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/davidliu/.virtualenvs/default3/lib/python3.5/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/davidliu/.virtualenvs/default3/lib/python3.5/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/Users/davidliu/Website/HMH-project/app/routes.py", line 226, in create
    return render_template('create.html', title = 'Create New Entry', form = form)
  File "/Users/davidliu/.virtualenvs/default3/lib/python3.5/site-packages/flask/templating.py", line 134, in render_template
    context, ctx.app)
  File "/Users/davidliu/.virtualenvs/default3/lib/python3.5/site-packages/flask/templating.py", line 116, in _render
    rv = template.render(context)
  File "/Users/davidliu/.virtualenvs/default3/lib/python3.5/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/Users/davidliu/.virtualenvs/default3/lib/python3.5/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/davidliu/.virtualenvs/default3/lib/python3.5/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/Users/davidliu/Website/HMH-project/app/templates/create.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/davidliu/Website/HMH-project/app/templates/base.html", line 2, in top-level template code
    {% import 'bootstrap/wtf.html' as wtf %}
  File "/Users/davidliu/.virtualenvs/default3/lib/python3.5/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 1, in top-level template code
    {% block doc -%}
  File "/Users/davidliu/.virtualenvs/default3/lib/python3.5/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 4, in block "doc"
    {%- block html %}
  File "/Users/davidliu/.virtualenvs/default3/lib/python3.5/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 20, in block "html"
    {% block body -%}
  File "/Users/davidliu/.virtualenvs/default3/lib/python3.5/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 23, in block "body"
    {% block content -%}
  File "/Users/davidliu/Website/HMH-project/app/templates/base.html", line 105, in block "content"
    {% block app_content %}{% endblock %}
  File "/Users/davidliu/Website/HMH-project/app/templates/create.html", line 29, in block "app_content"
    <form action="{% block form_action %}{{ url_for('entries') }}{% endblock %}" class="form-horizontal" method="post">
  File "/Users/davidliu/Website/HMH-project/app/templates/create.html", line 29, in block "form_action"
    <form action="{% block form_action %}{{ url_for('entries') }}{% endblock %}" class="form-horizontal" method="post">
  File "/Users/davidliu/.virtualenvs/default3/lib/python3.5/site-packages/flask/helpers.py", line 333, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/Users/davidliu/.virtualenvs/default3/lib/python3.5/site-packages/flask/app.py", line 1805, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/Users/davidliu/.virtualenvs/default3/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/Users/davidliu/.virtualenvs/default3/lib/python3.5/site-packages/flask/helpers.py", line 323, in url_for
    force_external=external)
  File "/Users/davidliu/.virtualenvs/default3/lib/python3.5/site-packages/werkzeug/routing.py", line 1768, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'entries'. Did you forget to specify values ['username']?
2018-02-04 02:53:20,527 INFO: WriteMind startup [in /Users/davidliu/Website/HMH-project/app/__init__.py:56]
